name: UnioCustomItems
main: me.uniodex.uniocustomitems.CustomItems
author: 'UnioDex'
version: 4.0
description: UnioCustomItems
depend: [Vault, WorldEdit, WorldGuard]
softdepend: [ShopGUIPlus, Essentials, LockettePro, Factions, UnioMarket, ASkyBlock, CombatTagPlus, TradeMe, UnioProtections, MythicMobs]

commands:
  uci:
    description: UnioCustomItems
  fly:
    description: Fly
  xpbottle:
    description: xpbottle
  vote:
    description: Vote
    aliases: [oy]
  catvision:
    description: CatVision
    aliases: [kedigörüşü, kedigözü, kedigozu, kedigorusu]
  energydrink:
    description: Energy Drink
    aliases: [enerjiiçeceği, enerji, enerjiicecegi]