name: UnioCustomItems
main: me.uniodex.uniocustomitems.CustomItems
author: 'UnioDex'
version: 5.0
description: UnioCustomItems
depend: [Vault, WorldEdit, WorldGuard, Essentials, UnioEssentials, UnioProtections]
softdepend: [ShopGUIPlus, LockettePro, Factions, UnioMarket, ASkyBlock, CombatLogX, TradeMe, MythicMobs]

commands:
  uci:
    description: UnioCustomItems
  xpbottle:
    description: xpbottle